version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: kedro.extras.logging.ColorHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
        colors:
            info: magenta

    console_ml_project:
        class: kedro.extras.logging.ColorHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
        colors:
            info: blue

    console_warning:
        class: kedro.extras.logging.ColorHandler
        level: WARNING
        formatter: simple
        stream: ext://sys.stdout
        colors:
            info: red

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

loggers:
    anyconfig:
        level: WARNING
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    kedro.io:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    kedro.pipeline:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    project:
        level: INFO
        handlers: [console_ml_project, info_file_handler]
        propagate: no

    ml_warning:
        level: WARNING
        handlers: [console_warning]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
