    # An example workflow configuration

    # The name of your workflow
    name: Publish and share Kedro Viz

    permissions:
        # The contents write permission is required to use the action
        # if your GitHub publishing source is a branch
        contents: write

        # The pages and id-token write permissions are required to use
        # the action if your GitHub publishing source is a custom
        # GitHub Actions workflow
        pages: write
        id-token: write

    on:
        # This can be configured based on your requirements
        # (i.e., the workflow trigger condition)
        pull_request:
        push:
            branches:
                - main
        workflow_dispatch:

    # We mentioned the minimal jobs for the workflow
    jobs:
        deploy:
            # The action is currently tested on ubuntu-latest (Recommended)
            runs-on: ubuntu-latest
            steps:
                - name: Fetch the repository
                  uses: actions/checkout@v4
                - name: Set up Python
                  uses: actions/setup-python@v5
                  with:
                    python-version: '3.10.13'
                    cache: 'pip'
                  # This installs the Kedro-project dependencies
                  # TEST
                - name: Install graphviz's requirements
                  run: sudo apt-get install -y python3-dev graphviz libgraphviz-dev pkg-config
                - name: Install requirements
                  run: pip install -r src/requirements.txt
                - name: Deploy Kedro-Viz to GH Pages
                  uses: kedro-org/publish-kedro-viz@v1
